### ISSUE TITLE
Notes element not in proper sequence for TCX files

### ISSUE THREAD

**Issue by credmp** [cpfair/tapiriik#120]
Hi,

I was writing some code to parse the TCX files that tapiriik stores on Dropbox for me. It failed validating the XML based on the XSD from Garmin.

Relevant part from the XSD:

		<xsd:sequence>
			<xsd:element name="Id" type="xsd:dateTime"/>
			<xsd:element name="Lap" type="ActivityLap_t" maxOccurs="unbounded"/>
			<xsd:element name="Notes" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Training" type="Training_t" minOccurs="0"/>
			<xsd:element name="Creator" type="AbstractSource_t" minOccurs="0"/>
			<xsd:element name="Extensions" type="Extensions_t" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>You can extend Training Center by adding your own elements from another schema here.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>

As you notice the sequence should be Id, Lap, Notes. The following XML was placed on Dropbox by Tapiriik:

    <Activities>
      <Activity Sport="Running">
        <Notes>30DL</Notes>
        <Id>2015-01-20T05:14:40.000Z</Id>
        <Lap StartTime="2015-01-20T05:14:40.000Z">

Resolving this will allow the parsing of generated TCX files by other software.

Regards

Arjen

**Comment by credmp** [comment]
Thanks for the fix! Any ideas when you will push it to production?

**Comment by cpfair** [comment]
Turns out I hadn't started the deploy when I thought I had - it should be live now.
