### ISSUE TITLE
Cannot link with RunKeeper

### ISSUE THREAD

**Issue by fabi1cazenave** [cpfair/tapiriik#123]
Linking Endomondo and Strava has been straight-forward, but I couldn’t link with RunKeeper.

Steps to reproduce:
* go to https://tapiriik.com/
* click on the RunKeeper “connect” link
* authenticate on RunKeeper
* click on the “Allow” button

Expected result: RunKeeper is allowed to sync
Actual result: Server Error (500)

I’ve tried a dozen times, same result. Tapiriik appears in RunKeeper apps but I cannot see it in the Tapiriik home page. I tried removing Tapiriik from RunKeeper and starting over again, without success.

**Comment by cpfair** [comment]
Give this another spin. FS problems on one of the sync servers yesterday led (quite circuitously) to the main database grinding to a halt. That server's been fixed, I've added some extra monitoring for the issue, and I'm working on a more durable fix should it happen again.

**Comment by fabi1cazenave** [comment]
Everythink works fine now, thanks for the quick reply. The result is amazing! Great tool.
