### ISSUE TITLE
SyntaxError: Non-ASCII character in file

### ISSUE THREAD

**Issue by markcs** [cpfair/tapiriik#125]
I just installed tapiriik, but it fails to start with the Non-ASCII character error, such as:

SyntaxError: Non-ASCII character '\xe1' in file /home/mark/git/tapiriik/tapiriik/settings.py on line 231, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

I'm sure this is an environment issue, but I'm unsure where to set this.

Thanks!

**Comment by Newman101** [comment]
It seems that UTF-8 encoding is not declared on the top of the .py file. Python uses ASCII encoding by default.

**Comment by cpfair** [comment]
Are you running Python 3k? I've never run into this issue in all the machines I've run it on.

**Comment by Newman101** [comment]
Yes, I am running Python 3 on both of my machines.

**Comment by Newman101** [comment]
Can you try running the following, please?

import sys
print sys.getdefaultencoding()

Then check the result and paste it here. 

Thanks.

**Comment by cpfair** [comment]
If that code executes as-is on your python interpreter, you aren't running Python 3. Nevertheless, both my personal machine and a production server show `utf-8`.

**Comment by markcs** [comment]
Apologies.  My Bad. 

Python 2.7 was the default.  Changing to Python 3 works ...
