### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by cagnulein** [cpfair/tapiriik#132]
What about sync tags too? 
I'm using endomondo and i have a lot of tags that i would like to share with my other services (Strava in first istance).

**Comment by cpfair** [comment]
What tags are you thinking of? Last I checked, Strava doesn't let users create their own tags beyond the built-in commute and trainer ones.

**Comment by cagnulein** [comment]
I thought that in strava the description field was searchable, but I was wrong.
