### ISSUE TITLE
Give an indication of how long the queue is

### ISSUE THREAD

**Issue by patcon** [cpfair/tapiriik#136]
Because waiting without an ETA is psychologically bad mojo :)

**Comment by cpfair** [comment]
This was once a thing, and had disappeared around the time I switched to RabbitMQ. But, I just put it back: https://github.com/cpfair/tapiriik/commit/8703b58699b103414529694b5d4653baec320cee

**Comment by patcon** [comment]
Wow. Thanks man! That was so quick
