### ISSUE TITLE
activities from Runkeeper contain multiple duplicate waypoints

### ISSUE THREAD

**Issue by campbellr** [cpfair/tapiriik#138]
I'm working on adding a smashrun sync service to Tapiriik (see https://github.com/campbellr/tapiriik/tree/smashrun for the WIP branch) and while debugging it I noticed that i was getting a bunch of track points (from Runkeper) that were essentially duplicates.

For example:

```
wp.Distance: 0 wp.Timestamp: 2015-06-17T19:39:29-08:00
wp.Distance: 0 wp.Timestamp: 2015-06-17T19:39:29.999000-08:00
wp.Distance: 0 wp.Timestamp: 2015-06-17T19:39:30-08:00
wp.Distance: 2.1068496910993506 wp.Timestamp: 2015-06-17T19:39:30.998000-08:00
wp.Distance: 2.1068496910993506 wp.Timestamp: 2015-06-17T19:39:31-08:00
wp.Distance: 2.850925872377977 wp.Timestamp: 2015-06-17T19:39:31.997000-08:00
wp.Distance: 2.850925872377977 wp.Timestamp: 2015-06-17T19:39:32-08:00
wp.Distance: 3.0787413813318176 wp.Timestamp: 2015-06-17T19:39:32.996000-08:00[INFO    ] wp.Distance: 3.0787413813318176 wp.Timestamp: 2015-06-17T19:39:33-08:00
wp.Distance: 3.9736914539725077 wp.Timestamp: 2015-06-17T19:39:33.995000-08:00
wp.Distance: 3.9736914539725077 wp.Timestamp: 2015-06-17T19:39:34-08:00
wp.Distance: 5.386387586576348 wp.Timestamp: 2015-06-17T19:39:34.994000-08:00
wp.Distance: 5.386387586576348 wp.Timestamp: 2015-06-17T19:39:35-08:00
wp.Distance: 7.055627827948492 wp.Timestamp: 2015-06-17T19:39:35.993000-08:00
```

I'm not sure yet if this is a problem with Runkeeper or the `RunkeeperService`, but it is a bit suspicious, and i verified that the GPX file downloaded from the runkeeper website doesn't contain any dupes (each track point is 1 second apart).

**Comment by cpfair** [comment]
`RunkeeperService` doesn't download the GPX, it fetches the raw data from their API - which can be in multiple streams at different sample rates. Since the internal data representation only supports a single stream of data, the incoming streams are reconciled without dropping any samples (see `stream_sampling.py`).

So, that's how you get seemingly-duplicate waypoints. I've never worried much about it, though.

**Comment by campbellr** [comment]
OK, that's a bit unfortunate, but i'll accept that it's a runkeeper quirk and move on with my life...

Thanks for the explanation.
