### ISSUE TITLE
Export to OpenStreetMap

### ISSUE THREAD

**Issue by rmikke** [cpfair/tapiriik#145]
Would it be possible to export gps traces to OSM? 
It should be one way process, because traces on OSM are not necessarily workouts.
But it would make mappers' lives so much easier :D

**Comment by cpfair** [comment]
You should be able to use the Dropbox connected and the TCX/GPX files it generates.

**Comment by rmikke** [comment]
Ummm... I don't understand.
I believe there is now no way to automatically upload GPX files from dropbox to openstreetmap.
And what I want to achieve is have my workouts automagically registered as gps traces on OSM..

**Comment by cpfair** [comment]
Yeah, no idea about uploading to OSM - I'm just saying that it's unlikely to ever be added as an official connection (2+ years and this is the first request for it) so that could be a passable workaround.

**Comment by rmikke** [comment]
OK, I'll check with other mappers if they like the idea.

**Comment by rmikke** [comment]
OK, it seems they didn't rush for it ;)
