### ISSUE TITLE
Runkeeper has new branding

### ISSUE THREAD

**Issue by cmnyc** [cpfair/tapiriik#157]
Runkeeper has new branding... logo, etc.
http://t.co/j0wFYE2toB

Time to update the Runkeeper button/logo on the site, as well as replace "RunKeeper" with "Runkeeper" (lowercase K.)

**Comment by cmnyc** [comment]
I think this casing of "RunKeeper" should change also within..."tapiriik
synchronizes your fitness activities between Garmin Connect, RunKeeper,
Strava, TrainingPeaks, SportTracks.mobi, Endomondo, RideWithGPS,
TrainerRoad, Motivato, Velo Hero, Epson RUNSENSE, Dropbox, and Smashrun"

**Comment by cpfair** [comment]
Oops - forgot about that, thanks!
