### ISSUE TITLE
Gym type Acitivities not sync'd to RunKeeper

### ISSUE THREAD

**Issue by slackspace-io** [cpfair/tapiriik#162]
There is a 'strength training' type listed on RunKeeper's API, but Tapiriik excludes all types 'Gym' from being sync'd to RunKeeper.

Can this be supported? Specifically this is new strength training activities in Garmin Connect not syncing to RunKeeper synce the activity is not supported per Tapiriik's site.

**Comment by cpfair** [comment]
This is by design, because tapiriik can't sync which exercises you did, etc. - all you'd see is a duration, which I decided was too useless to bother syncing.

**Comment by jpyth** [comment]
Eh, agree the data isn't that useful. But for tracking total activity time it is somewhat useful. Which is the main reason I wanted this activity to sync.

As well if you wear an HRM it will do HR/Calories in Garmin.

**Comment by cpfair** [comment]
I'd rather sync the activities properly the first time, rather than littering everyone's accounts with marginally useful activities (especially if I ever do add support for more complex training activities - at which point I couldn't modify/delete the ones I'd already uploaded).

**Comment by jtriz** [comment]
Collin - Any chance you'll reconsider this change? I use the Garmin "Other" activity type to track HIIT workouts indoors but when I sync them to Runkeeper, they appear as zero duration activities. I'd like to see the duration of these activities to capture a more complete picture of my workouts in Runkeeper. Hope you'll consider it!

**Comment by kashev** [comment]
Are there any services on the tapiriik list which do allow you to track what exercises you did in a strength training session?

**Comment by patrickplaggenborg** [comment]
Wouldn't the ones already logged be 'simple' activities forever?

These simple 'duration only' activities are extremely useful right now to keep track of the amount of activities in total.

Syncing duration activities right now would be great.

Later, when more detail is supported for these activity types, syncing newer activities of this type could simply keep the old ones in tact and allow for more fine grained info in the new activities?

Then we have a great solution for now that works for the current platforms, which can be compatible with more detail in the future?

**Comment by guenteri** [comment]
Sorry for bringing up that issue again ;)

I record every gym session in garmin connect. Sometimes i wear a heart rate belt and the most time i add some short notes about the kind of strength training.

Even if only the date/time and duration has been recorded, this is an important information for statistic purposes and training documentation. I think that the people who record their gym sessions in any service would like to sync it to other services. In my case i would like a dropbox export for further use of the data on a local installed training documentation system.

Maybe an option like the "sync privat activities" checkmark  on garmin connect service would be a good thing. So the users have the freedom to choose what they want. 

So maybe you consider a sync of "Gym" and "StrengthTraining" sessions.

**Comment by slackspace-io** [comment]
Closing this since it's 8 years old, with most recent comment being 7 years old :)
