### ISSUE TITLE
What endomondo API-keys should I use for my local hosted instance?

### ISSUE THREAD

**Issue by fredrike** [cpfair/tapiriik#169]
Really love tapiriik but like to host my own instance and I can't figure out where to register an app on endomondo to fill the ENDOMONDO_CLIENT_KEY and ENDOMONDO_CLIENT_SECRET.

**Comment by cpfair** [comment]
You need to contact them directly via email.

**Comment by larssb** [comment]
Hi @fredrike - did you succeed? Want to do the same and was just curious into how much this is going to become a hassle.

Thank you very much.

**Comment by fredrike** [comment]
Hi @larssb, no I lost interest in the project as it seemed too much of an effort to get the keys from endomondo.

**Comment by larssb** [comment]
On Wed, May 25, 2016 at 8:26 AM, Fredrik Erlandsson <
notifications@github.com> wrote:

> n the project as it seemed too much of an effort to get the keys from
> endomondo.


Hi Fredrik,

I understand. Thank you for getting back to me.


-- 
Mvh. / Kind regards
Lars Bengtsson

- Health is wealth, movement is medicine -
