### ISSUE TITLE
Syntax error(?) in autopause.py

### ISSUE THREAD

**Issue by abhijit86k** [cpfair/tapiriik#180]
Started up the server, no errors or warnings:
>System check identified no issues (0 silenced).
>September 23, 2015 - 01:43:37
>Django version 1.8.4, using settings 'tapiriik.settings'
>Starting development server at http://0.0.0.0:8000/
>Quit the server with CONTROL-C.

But when open the site in my browser, however, i get this syntax error. I'm using the source from master (9d89d2d066), and I had to export PYTHONPATH=./tap-env/lib/python2.7/site-packages.

>  File "<INSTALL_PATH>/Source/tapiriik/tap-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 52, in load_middleware
>     mw_instance = mw_class()
>   File "<INSTALL_PATH>/Source/tapiriik/tapiriik/web/startup.py", line 8, in __init__
>     from tapiriik.services import Service
>   File "/usr/lib/python3.2/importlib/_bootstrap.py", line 436, in load_module
>     return self._load_module(fullname)
>   File "/usr/lib/python3.2/importlib/_bootstrap.py", line 141, in decorated
>     return fxn(self, module, *args, **kwargs)
>   File "/usr/lib/python3.2/importlib/_bootstrap.py", line 342, in _load_module
>     exec(code_object, module.__dict__)
>   File "<INSTALL_PATH>/Source/tapiriik/tapiriik/services/__init__.py", line 3, in <module>
>     from tapiriik.services.RunKeeper import RunKeeperService
>   File "<INSTALL_PATH>/Source/tapiriik/tapiriik/services/RunKeeper/__init__.py", line 1, in <module>
>     from .runkeeper import *
>   File "<INSTALL_PATH>/Source/tapiriik/tapiriik/services/RunKeeper/runkeeper.py", line 5, in <module>
>     from tapiriik.services.auto_pause import AutoPauseCalculator
>   File "<INSTALL_PATH>/Source/tapiriik/tapiriik/services/auto_pause.py", line 15
>     yield from ()
>              ^
> SyntaxError: invalid syntax

**Comment by cpfair** [comment]
`yield from` is new in Python 3.3 - make sure you're up-to-date.

**Comment by abhijit86k** [comment]
Doh right.
Need to compile py3.3 from source i guess. Thanks @cpfair .
