### ISSUE TITLE
Tapiriik unable to connect to Garmin Connect anymore

### ISSUE THREAD

**Issue by texaschip** [cpfair/tapiriik#205]
I have not been able to sync my activities to/from Garmin Connect in a long time.  The activities log shows an "x" by GC.  Other linked services are fine.  I tried disconnecting GC and reconnecting it from the tapiriik dashboard.  I even tried removing the "tapiriik sync" connection from GC (it was later re-added when I reconnected GC in the tapiriik dashboard).  Can you please help?  I really love tapiriik and I've been using it for a couple of years and recommended it to many friends, but without GC its value is greatly diminished for me (I use GC as the primary repository of my activities). 

My tapiriik user ID is 54ab5016cbe97e44ee816a41 

Thanks a lot !!!

**Comment by cpfair** [comment]
GC connection itself was working fine, just an error related to your account (any anyone else with a tennis, ATV, or RC drone activity, among others). Should fix itself at next sync.

**Comment by texaschip** [comment]
Confirming issue has been resolved. Thanks a lot for your prompt help!
