### ISSUE TITLE
Tapiriik dashboard shows "Queuing".

### ISSUE THREAD

**Issue by MattB111** [cpfair/tapiriik#210]
Not sure where the problem is, but the Tapiriik dashboard just shows "Queuing".

I have activities on Saturday 5th March which synced ok (Strava to Garmin connect), but all activities later than this haven't synced.

**Comment by ivarkoster** [comment]
I also have the same issue. Last successful sync was the 4th of March. Two activities on Sunday the 6th of march are kept in the queue and are not being processed.

**Comment by hmsuchier** [comment]
Same issue here... yesterday activity was not sync'd from GC to Runkeeper nor Strava.

**Comment by mvillemot** [comment]
Same issue here. No sync at all and the Queing is still diplayed.

**Comment by wwcsig** [comment]
Same here - "Queueing", last updates synced on March 5.

**Comment by mow4cash** [comment]
Same here - "Queueing", last updates synced on March 5.

**Comment by cpfair** [comment]
Sorry, was without Internet all weekend during which the scheduler process froze. Restarted it and will investigate the underlying problem.





On Mon, Mar 7, 2016 at 9:33 AM -0800, "mow4cash" <notifications@github.com> wrote:












Same here - "Queueing", last updates synced on March 5.

**Comment by hmsuchier** [comment]
Hey, it just synced few minutes ago. It seems that you're working on it right now, thanks for the great job !

**Comment by u46221** [comment]
Working for me as well kudos

**Comment by MattB111** [comment]
Excellent thank you. All working again now.

**Comment by ivarkoster** [comment]
You rock!

**Comment by rwa** [comment]
Seems to still be an issue with smashrun for me.  Says it synced a March
5th run, but it doesn't show in SR, then all subsequent activities show
that they didn't sync.
