### ISSUE TITLE
Link with Runkeeper didn't work

### ISSUE THREAD

**Issue by Aptahar** [cpfair/tapiriik#230]
After clicking "Allow" on Runkeper website, it goes to 404 page. Link is shown in app section on Runkeeper site, but not on tapiriik.
Connect to Endomondo and dropbox without any problem.

Trying last 4 days

**Comment by kristofferh** [comment]
Same issue for me.

**Comment by cpfair** [comment]
I haven't been able to replicate this, I just tried disconnecting and reconnecting a RunKeeper account several times without issue. So the 404 occurs after you click "Accept" on the RunKeeper site - what URL is in the address bar at that point?

**Comment by Aptahar** [comment]
https://runkeeper.com/apps/authorize?allow=

**Comment by cpfair** [comment]
Strange - can you connect to other apps with RunKeeper integration?

**Comment by Aptahar** [comment]
Runkeeper full of issues, as always..) Will report to them, thnx.
