### ISSUE TITLE
Cant authorize with Runkeeper

### ISSUE THREAD

**Issue by iagommc** [cpfair/tapiriik#231]
I'm getting a 404 page after click on "Allow" button.
After click on "Allow" i get 404 on this page "https://runkeeper.com/apps/authorize?allow="

**Comment by cpfair** [comment]
Seems to be the same issue as #230, but I don't really have any ideas beyond contacting RK's support. I've never seen it myself on any of my accounts.

**Comment by ledermann** [comment]
This was an issue for me, too, so I contacted RunKeeper's support. They just told me that it's fixed now.
It works for me, authorizing doesn't fail anymore. This issue can be closed, IMHO.

**Comment by iagommc** [comment]
Me too, now is working fine.


--
Iago Macedo
+55 (85) 99903-0830
iagommc@me.com
http://iagomacedo.com.br

Em 2 de jun de 2016 04:43 -0300, Georg Ledermann<notifications@github.com>, escreveu:

**Comment by cpfair** [comment]
Good to hear!
