### ISSUE TITLE
Sync Strava->TrainingPeaks not working, just reads "Queuing"

### ISSUE THREAD

**Issue by alphaleonis** [cpfair/tapiriik#243]
I had several services connected, and suddenly synchronization seemed to stop working. I have payed and have automatic sync enabled. I disconnected all services, and reconnected only Strava and TrainingPeaks (with sync from Strava to TrainingPeaks) but still no synchronization seems to happen. Whenever I go to the tapiriik website, it only says "Queuing" at the top, and has been for a day or two now at least.

**Comment by cpfair** [comment]
Sorry, I had neglected to post an update on twitter clarifying that synchronizations were not running due to issues at my hosting provider and a failure of an automatic failover. Took a while to get things sorted out, but everything's working again now I believe.
