### ISSUE TITLE
Garmin Connect

### ISSUE THREAD

**Issue by meeximum** [cpfair/tapiriik#254]
Login doesn't work anymore :-/

**Comment by cpfair** [comment]
Can you try logging into your Garmin Connect account (on their site) from
an incognito window? I just tried that and got this message -
http://ss.cpfx.ca/NBx3PRwi.png - which might be your issue. If it is I'll
add a better error message than "There was a problem" for that case.

**Comment by meeximum** [comment]
Bingo, that solved my problem!
Thanx
