### ISSUE TITLE
garmin account not connecting

### ISSUE THREAD

**Issue by bwgooch** [cpfair/tapiriik#255]
Tapiriiik login to my Garmin account suddenly not working.  When I try to connect to Garmin on the tapiriik page I get the message "There was a problem logging you in".  There were no changes by me to any account settings in Garmin, when I logged into the Tapiriik page it said that I needed to reauthorize my Garmin account, but when I tried to I got the preceding message.  I have tried disconnecting Garmin account in Tapiriik, now I cannot reconnect.

**Comment by cpfair** [comment]
Sounds like the same problem as #254 - I just updated the site to give a
proper error message in this case (when you need to visit Garmin Connect
directly to reset your password).

**Comment by bwgooch** [comment]
Thanks, that was it.  Changed my password and all good again.
