### ISSUE TITLE
Endomondo to Strava, privacy flag not granted

### ISSUE THREAD

**Issue by dfad1ripe** [cpfair/tapiriik#264]
When syncing from Endomondo to Strava, all activities marked as private in Endomondo have been created as public in Strava.

The FAQ says: "tapiriik tries to keep private activities private, but not all services support private activities". However, according to http://strava.github.io/api/v3/uploads/, Strava API supports creating activities as private via API.

**Comment by cpfair** [comment]
Strava supports it, [but Endomondo doesn't](https://github.com/cpfair/tapiriik/blob/master/tapiriik/services/Endomondo/endomondo.py).
