### ISSUE TITLE
Can't sync smashrun to strava or training peaks

### ISSUE THREAD

**Issue by MokoPolo** [cpfair/tapiriik#271]
![image](https://cloud.githubusercontent.com/assets/3758891/20465399/576cc60e-af2a-11e6-857d-470473c8ad36.png)

It just says this activity contains unusual data that is most likely incorrect.

Not sure what the problem is. Can confirm that the workout is on smashrun..

**Comment by WoBaDijk** [comment]
Same problem here when syncing my dad's runs, but then from Smashrun to Strava and Runkeeper. For me the Smashrun data comes from Nike+. The error message appeared with more or less 500 of his 950 runs.
