### ISSUE TITLE
Re-sending activities

### ISSUE THREAD

**Issue by 2manydjs** [cpfair/tapiriik#281]
Hi,

At the moment my main tracking device is a Garmin Vivosmart HR+.  It tracks reasonably well, but sometimes it jumps around a bit.  Garmin Connect has no functionality to edit and correct the GPS data points, but Runkeeper does.  I had intended on the following workflow: 1. Run w Garmin, 2. synchronize the run to Runkeeper, 3. edit the data on Runkeeper, 4. delete the run on Garmin, 5. push the corrected data back to Garmin from Runkeeper.

It is the last step that doesn't work for me.  The log file shows a tickbox for the deleted run on Garmin, even though it's no longer there.  Can I force tapiriik to send the run data (which includes HR info, unlike the GPX) back to Garmin?

I am using tapiriik.com, but don't mind running it locally if it gives me this option.

Mark

**Comment by joaoe** [comment]
I have the same issue. Sometimes I edit activities, or reupload them, and they are not correctly synchronized (edits or deletes+adds).

**Comment by cpfair** [comment]
Once an activity is synchronized it is never touched again, for practical reasons (it's expensive to check if the activity has been edited, and not all platforms support edition, etc.).
