### ISSUE TITLE
Unable to start sync on tapiriik.com

### ISSUE THREAD

**Issue by np1** [cpfair/tapiriik#323]
There is no sync button showing and the activity history is not displaying. I have tried with a couple of different browsers and on mobile, all have the same issue.

![screenshot_2017-04-23_11-50-55](https://cloud.githubusercontent.com/assets/2274410/25309898/d7e7da5c-281b-11e7-8417-ad0e6c5fa0e4.png)

**Comment by mow4cash** [comment]
same issue here

**Comment by cpfair** [comment]
A deploy failed and left the web servers in a bad state - fixed now, sorry!
