### ISSUE TITLE
Add support for Samsung Health

### ISSUE THREAD

**Issue by daroczig** [cpfair/tapiriik#325]
Hi, first of all -- thanks for this great project, I've been a happy user syncing Endomondo and Dropbox for a bit more than a year. I'm thinking about switching to the Samsung ecosystem. Any chance to add support for syncing to and from Samsung Health?

**Comment by cpfair** [comment]
There does not appear to be any web-based S Health API (there is an SDK - but it's only for phone apps running locally). So, probably not.

**Comment by daroczig** [comment]
That's a shame :disappointed: 
And I hope this situation will change soon, but please feel free to close this ticket.
