### ISSUE TITLE
Problem with send to Endomondo

### ISSUE THREAD

**Issue by es1o** [cpfair/tapiriik#345]
Hi, tapirik has stopped send activities to endomondo and runkeeper since 22th June. Sending to Dropbox works properly.

**Comment by maakuth** [comment]
It does seem like there is something wrong with Endomondo sync. My last synced activity from Endomondo was on June the 21st, nothing has come through since.

**Comment by mtomana** [comment]
My running activities are working correctly (last sync Strava->Endomondo from 10th July was successful).

**Comment by maakuth** [comment]
@es1o it does seem that it works in my case when I do manual sync, but not automatically.

**Comment by Daszczu** [comment]
Manual or automated, I'm stuck at Queuing. I've reconfigured again the permissions and reclaimed the paypal donation - no luck.
My Strava activities haven't synced to Endomondo since 7th of July

**Comment by mtomana** [comment]
@Daszczu, what type of activities can't sync? Because my running/cycling activities work fine but inline skating - nope :(

**Comment by Daszczu** [comment]
@mtomana few newest running activities are missing. 
Funny thing is that a rowing activity from 2015 has just synced ;)
