### ISSUE TITLE
Garmin Sync Broken Again (Jul-17)

### ISSUE THREAD

**Issue by RobDickson** [cpfair/tapiriik#360]
It might be a coincidence, but the Garmin Sync stopped working about the same time that the Strava and Endomondo bug was fixed.

https://twitter.com/tapiriik/status/887495741450706944

Up until then, it had worked OK for about a month and a half.

**Comment by MattB111** [comment]
Strava to Garmin sync is working fine for me.

What issue are you seeing with Garmin Sync not working?

**Comment by RobDickson** [comment]
It was Garmin to anything else that stopped working for about a week. It's working again now.

**Comment by h3xstream** [comment]
Quick note : Garmin new UI does not allow to make activities visible to connections.

**Comment by RobDickson** [comment]
@Philippe Arteau: What "new Garmin UI" is causing you problems?

> Quick note : Garmin new UI does not allow to make activities visible to connections.

**Comment by h3xstream** [comment]
@RobDickson My mistake .. It is still possible to edit the visibility but every activities need to be edited one by one.

**Comment by RobDickson** [comment]
That's why I haven't noticed the problem - I only ever want to change one activity at a time.

**Comment by h3xstream** [comment]
The sync is working for me after changing the visibility.
