### ISSUE TITLE
from Runkeeper, API Rate Limit

### ISSUE THREAD

**Issue by Seto-san** [cpfair/tapiriik#384]
hi,
Synchronization from Runkeeper to STRAVA will fail with the following error;

> There was a problem logging you into Runkeeper: 
> 
> Failed to retrieve RK user metadata 429: {"reason":"Rate-limit exceeded. rate limit is **300000 calls per days1**"} (user None )
> 
> Try logging in again - it might just be a temporary problem connecting to Runkeeper. If that doesn't help, try connecting this account using a different browser or device.

At the other time, the following;

> Failed to retrieve RK user metadata 429: {"reason":"Rate-limit exceeded. rate limit is **5000 calls per 15 minutes**"} (user None )

------------
cf:[Runkeeper Developers Website](https://developer.runkeeper.com/healthgraph/overview#rate-limits)
> **Rate Limits**
> Rate limiting of the API is applied mostly on a per-user token basis. There are also global per-application rate limits that are reset daily. When an app has exceeded a particular rate limit, a 429 status code will be returned along with a message containing details of the rate limit. You should design your application to make API calls only when absolutely necessary and use the API as efficiently as possible. If you are hitting rate limits, here are some techniques that can be implemented to address this:
> 
> **Caching**
> Store API responses in your application or on your site if you expect to read the same data or resources often.
>
> **Prioritize active users**
> If your application has many users, consider only requesting data for users who have recently been active.
>
> If you have taken the above measures and still have a need for increased rate limits, contact api@runkeeper.com to discuss your use case. 
------------

I stopped Auto-sync, and retried logging-in 30 hours after logged-out, but the same error occurred.

Since (user None) in the error message and the error before login, I guesss it is not an error per-user limit, but the restriction on the entire tapiriik site is over.

**Comment by cpfair** [comment]
Same issue as #362
