### ISSUE TITLE
Cannot connect to Runkeep

### ISSUE THREAD

**Issue by Heykawa** [cpfair/tapiriik#385]
Hello

I am new to Tapirrik. I was able to connect to Strava with Tapirrik without any problem.
However, when I try to connect to Runkeeper with Tapirrik, I have an error message and I never was able to proceed to a connection. Precision : on the runkeeper login page, I use the "login with facebook option".

Here is the error message I receive :
_There was a problem logging you into Runkeeper: 
Failed to retrieve RK user metadata 429: {"reason":"Rate-limit exceeded. rate limit is 300000 calls per days1"} (user None )_

I couldn't see this issue in the list of known or open issues. I am the only one not able to connect to Runkeeper ?

Thank you

**Comment by strawpants** [comment]
Can confirm, this happens since last week. I tried removing and adding tapiriik from RK apps but, this didn't work either. Tried from opera and firefox

**Comment by cpfair** [comment]
Same issue as #362
