### ISSUE TITLE
'Queuing' since about a week

### ISSUE THREAD

**Issue by habi** [cpfair/tapiriik#416]
I saw that since about a week my activities are not synchronized from Garmin to Strava.
I checked several times on the website, but Tapiriik is always 'Queuing'.
I've removed *all* connections and added them back, this didn't change anything.

(I've paid for automatic synchronization).

**Comment by Antash** [comment]
Garmin Connect is broken right now. I am experiencing the same problem on my fork
https://github.com/Antash/tapiriik

Will invest some effort to fix it asap. May be we have a little chance @cpfair will merge the fix. :)

**Comment by Ballou** [comment]
@Antash are you having the same issue I am where I can't see the DropBox/App subfolders, in addition to not being able to get GC to sync?

**Comment by Antash** [comment]
Folks, the issue is pretty easy - garmin stopped supporting used api to list activities.
Easy fix. @cpfair if you are hear me could you please address all latest garmin issues here?

**Comment by KyleOndy** [comment]
It appears that the [activity list endpoint](http://connect.garmin.com/proxy/activity-search-service-1.0/json/activities?&start=0&limit=50) ([found here](https://github.com/cpfair/tapiriik/blob/master/tapiriik/services/GarminConnect/garminconnect.py#L289)) isn't returning any of my rides after the 21st of March.

Maybe it is Garmin that is having the issue?

**Comment by Antash** [comment]
Exactly. Tapiriik in case of garmin is a hacky tool which behaves like a human web client and uses internal API. Garmin stopped supporting non modern api endpoints sins 2x march so tapiriik should move to modern api. Currently in testing, will create pull-request soon

**Comment by habi** [comment]
Thanks!
