### ISSUE TITLE
DropBox App Subfolders Unavailable

### ISSUE THREAD

**Issue by Ballou** [cpfair/tapiriik#428]
In the Tapiriik UI for Dropbox, even when full access to Dropbox has been enabled, I can no longer view or direct sync to 3rd level subfolders or deeper.

I sync from Garmin Connect to a subfolder of Dropbox (DropBox/Apps/iSmoothRun/Import). I can direct sync to send to the default Tapiriik folder, but when full access is enabled I can only direct to the main 1st level folder for DB, the 2nd level of Apps, but nothing on a 3rd level (i.e. subfolders of Apps).

This had been working without fail for years. I have tried this in both Safari Version 11.1 (11605.1.33.1.3) & Firefox 59.0.2 (64-bit). 

Please advise @cpfair. Thanks!

Reference photos from Safari:

**Root Folder shows subfolders.**
![rootfolder](https://user-images.githubusercontent.com/9001808/38388858-5d228192-38d1-11e8-9a1f-fd95ea0453d0.jpg)

**But 2nd level subfolders show nothing (though there are confirmed folders present)**
![nosubfolders](https://user-images.githubusercontent.com/9001808/38388764-09848dd2-38d1-11e8-8306-99ae045cbe27.jpg)

**Here is the WebUi for DropBox showing there are indeed contents in this folder**
![dbwebui](https://user-images.githubusercontent.com/9001808/38389064-13bdf29c-38d2-11e8-824e-fc84b358baa6.jpg)

**Comment by cpfair** [comment]
Fixed in fbecf0122fc2d48e27a93d76788a50dfd84fcbd7 - sorry!
