### ISSUE TITLE
Can't disconnect Strava

### ISSUE THREAD

**Issue by SimonOsipov** [cpfair/tapiriik#433]
I have 3 services connected: GC, Strava, and TP.
I would like to disconnect Strava, but when I click on "Disconnect", nothing happens.
Disconnect become disable button and that is all.

**Comment by Antash** [comment]
Most likely strava cannot accept your client key. Need to run sync rpocess (change date for today before) and tapiriik should ask you to reauth strava client. Than you should be able to disconnect.

**Comment by SimonOsipov** [comment]
It asking me to the re-auth client, but when I do auth on Strava site, it returns 500 error.

**Comment by SimonOsipov** [comment]
@Antash was right, Strava did not recognize client key properly.
Disconnecting and connecting back to in different browser helped.
