### ISSUE TITLE
Smashrun API Integration

### ISSUE THREAD

**Issue by chrislukic** [cpfair/tapiriik#448]
@campbellr, 

I've been going through our API log files recently and I noticed something interesting. There seems to be 3 types of requests coming from Tapiriik currently.

1) Requests like these below that get an individual activity (makes sense)
```
2018-07-13 01:11:11 GET /v1/my/activities/5815260 - - 69.164.208.235 HTTP/1.1 tapiriik-prod - 200 0 0 1061
2018-07-13 01:11:11 GET /v1/my/activities/5815261 - - 69.164.208.235 HTTP/1.1 tapiriik-prod - 200 0 0 1061
2018-07-13 01:11:11 GET /v1/my/activities/5815262 - - 69.164.208.235 HTTP/1.1 tapiriik-prod - 200 0 0 1061

```
2) Requests like these that iterate over a few pages and then stop, presumably syncing new runs to an existing account (note the order of the page/count parameters).
```
2018-07-13 01:11:19 GET /v1/my/activities/search page=0&count=10 - 23.239.10.22 HTTP/1.1 tapiriik-prod - 200 0 0 7637
2018-07-13 01:11:19 GET /v1/my/activities/search page=1&count=10 - 23.239.10.22 HTTP/1.1 tapiriik-prod - 200 0 0 7637
2018-07-13 01:11:19 GET /v1/my/activities/search page=2&count=10 - 23.239.10.22 HTTP/1.1 tapiriik-prod - 200 0 0 7637
```

3) Requests that iterate over all the activities for a user to exhaustion, presumably these are new accounts. (note the parameters are reversed count/page)
```
2018-07-13 01:10:46 GET /v1/my/activities/search page=69&count=10 - 66.228.41.24 HTTP/1.1 tapiriik-prod - 200 0 0 8453
2018-07-13 01:10:46 GET /v1/my/activities/search page=70&count=10 - 66.228.41.24 HTTP/1.1 tapiriik-prod - 200 0 0 8245
2018-07-13 01:10:47 GET /v1/my/activities/search page=71&count=10 - 66.228.41.24 HTTP/1.1 tapiriik-prod - 200 0 0 8437
2018-07-13 01:10:47 GET /v1/my/activities/search page=72&count=10 - 66.228.41.24 HTTP/1.1 tapiriik-prod - 200 0 0 8437
2018-07-13 01:10:47 GET /v1/my/activities/search page=73&count=10 - 66.228.41.24 HTTP/1.1 tapiriik-prod - 200 0 0 8453
```

I was wondering if it would be possible for you to make a change to the Tapiriik integration so that the 3rd type of call is just made once, omitting the page and count parameters entirely and retrieving the users entire dataset in one batch? That would help to significantly reduce the volume of calls we're receiving.

That said in reviewing the logs, I'm really surprised at the % of full syncs I'm seeing. I would expect it to be a relatively rare occurrence when a new users registers, but in reality it appears that about 25% of the calls are full syncs. Any thoughts on this @cpfair?

**Comment by campbellr** [comment]
Hi @chrislukic,

> I was wondering if it would be possible for you to make a change to the Tapiriik integration so that the 3rd type of call is just made once, omitting the page and count parameters entirely and retrieving the users entire dataset in one batch? That would help to significantly reduce the volume of calls we're receiving.

That's definitely possible. When tapiriik syncs it will either do an 'exhaustive' sync, or a partial sync. I can't remember exactly what triggers an exhaustive sync vs a partial sync (so i can't comment on the unusual number of exhaustive syncs -- hopefully @cpfair can shed some light on that), but in both situations we page through the results using the default page size (10) defined in [campbellr/smashrun-client](https://github.com/campbellr/smashrun-client). See https://github.com/cpfair/tapiriik/blob/master/tapiriik/services/Smashrun/smashrun.py#L136 for the exact details.

For partial syncs we bail out early after we fetch the first 20 results.

It would be a trivial change to either increase the page size or return everything in one go when an exhaustive sync is triggered if you would prefer.

**Comment by campbellr** [comment]
@svdberg it is most likely an issue with tapiriik (or more likely, just the smashrun sync service).

Taking a quick look at the sync code though, it looks like we completely ignore power data, so that might not be the actual reason your runs are failing to sync (unless there is a bug somewhere else in tapiriik).

The smashrun service in tapiriik currently only syncs:

* distance
* clock
* latitude
* longitude
* elevation
* cadence
* heartRate
* temperature

I can't remember if that's because the smashrun api only supported those at the time, or if it was because i didn't have any way of testing the other measurements. Probably the latter.

**Comment by chrislukic** [comment]
@campbellr I think switching the exhaustive sync to simply return all activities rather than paging through them would cut the number of http requests at least an order of magnitude maybe more.
`https://api.smashrun.com/v1/my/activities`

Also combing through the logs it appears that the regular (not exhaustive) sync never makes fewer than 3 calls, always paging through at least the first 30 records. No idea why this would be, but given this I think switch the count from 10 to 30 makes sense.

I'm embarrassed that I don't know how to make/test this change myself. If you're able to find some time to make it at some point I'd really appreciate it.

Thanks,
Chris

**Comment by campbellr** [comment]
@chrislukic sure I will make a PR for those changes.

**Comment by xuopled** [comment]
Am I the only one having trouble to upload new activities to Smashrun ?

**Comment by chrislukic** [comment]
Thanks @campbellr!

**Comment by cixelsyd** [comment]
Woo-hoo!  *as the smashrun servers sigh with relief* Thanks, @campbellr !

**Comment by campbellr** [comment]
Sorry folks, that's just on my private fork right now. I just need to do some testing and then I'll create a PR to get it merged in here.

**Comment by xuopled** [comment]
Smashrun sync seems working since June, 8. Why not merging this PR? Maybe it will fix the sync
