### ISSUE TITLE
Sync: Upload only implementation?

### ISSUE THREAD

**Issue by gerhardol** [cpfair/tapiriik#450]
I am investigating the possibility to use Tapiriik to upload from an app to Tapiriik.
This is for RunnerUp Android app: https://github.com/jonasoreland/runnerup
The app has implemented integration (upload) to many services, most are no longer working though.
The current way to interact with Tapiriik is to upload to one of the working services like Strava and go from there. (Strava has limitations, maybe Dropbox could be used instead but that would require writing ti the Tapiriik app folder.)

Direct access will obviously only upload to Tapiriik, no pushing activities to RunnerUp.
The setup will be very different from the poll used by Tapiriik for other services.
Another difference is that there are no authorization server for the app itself, that has to be done indirectly from other services.

One solution is of course to embed Tapiriik in the app.
However, I would prefer to not do that, quite big step.
(A forked public Tapiriik server is not an option.)

**Comment by cpfair** [comment]
tapiriik doesn't have any means to accept and store activities until they can be transferred to the destination - it's purely in-memory from one service to another. As such, I think the Dropbox approach is probably best here.

**Comment by gerhardol** [comment]
Thanks for clarifying
