### ISSUE TITLE
How to pay the $2

### ISSUE THREAD

**Issue by bobsica** [cpfair/tapiriik#464]
I would like to renew my subscription and have searched every part of every available page and can't find anywhere to do that. Perhaps this is a Safari issue and something is being blocked?

Please let me know how I can pay so my auto-synching does not stop. Possible worth putting how to do this on the FAQ?

Thanks for your work on tapiriik.

Bob

**Comment by cpfair** [comment]
A longstanding limitation with the payment system means the link to purchase another year of service only reappears after the prior year's payment expires.

**Comment by bobsica** [comment]
Thanks, I look forward to renewing.
