### ISSUE TITLE
Private Activities Incorrectly Synchronising

### ISSUE THREAD

**Issue by RobDickson** [cpfair/tapiriik#517]
Eventually, tapiriik has managed to synchronise with Garmin Connect. Unfortunately, all it has done is synchronise 4 private activities to Strava.

Firstly, I have the sync to Strava set to not synchronise private activities.

Secondly, the four private activities were made public in Strava.

https://connect.garmin.com/modern/activity/4115470405
https://connect.garmin.com/modern/activity/4118513907
https://connect.garmin.com/modern/activity/4121737870
https://connect.garmin.com/modern/activity/4125732219

There are many other private activities that haven't been synchronised to Strava (yet).

**Comment by RobDickson** [comment]
It hasn't synchronised again (correctly or incorrectly) since then.

**Comment by RobDickson** [comment]
It happened again yesterday:
https://connect.garmin.com/modern/activity/4137451515

**Comment by cpfair** [comment]
This is another limitation with the new Garmin Connect API, in that tapiriik does not know which activities are private and which are not. Hence, the option to disable synchronization of private activities was never included in the new Garmin Connect configuration panel. I just updated the tapiriik dashboard to include a note calling attention to this limitation.

Unfortunately, in communication with the Garmin Connect API team, it doesn't seem like there is any resolution coming in the short term.
