### ISSUE TITLE
Not Synchronising Names and Notes from Garmin Connect

### ISSUE THREAD

**Issue by RobDickson** [cpfair/tapiriik#518]
Tapiriik has synchronised one activity from Garmin Connect. Although the activity is now in Strava OK, it hasn't synchronised the activity name and notes that I entered into Garmin Connect. Tapiriik always used to synchronise these changes fine, which was the main reason that I continued using Tapiriik after Garmin introduced its new synchronise to Strava (according to @AndreEpe, the Garmin Sync doesn't do this).

Is this a limitation of the new Garmin API, or is it something we're likely to see implemented in Tapiriik again soon?

https://connect.garmin.com/modern/activity/4141024509
https://www.strava.com/activities/2776782210

**Comment by cpfair** [comment]
Yes, this is a limitation with the new Garmin Connect API. Based on conversations with their team, it doesn't seem like the feature will be added soon, unfortunately.
