### ISSUE TITLE
Cannot sync to/from Strava at all

### ISSUE THREAD

**Issue by jeaton2i** [cpfair/tapiriik#529]
I am continuing to have issues getting data to sync with Strava.  

The last successful time anything was synced to Strava was my July 16, 2019 activity.  I have tried numerous things, including unlinking and re-linking all of my services.   I cannot actually unlink Strava from tapiriik, because the unlink page makes an XHR request that gets back a 500 error from URL: https://tapiriik.com/#/disconnect/strava but I did revoke the rights on the Strava side, then reconnected from tapiriik.

The activities page says:

Strava: There was a problem indexing your activities on Strava, so no activities will be uploaded to Strava.

I don't even care about uploading to Strava.  I use the Strava app to record my runs, and I really want something to sync from Strava to other services.  I'm even a paid tapiriik user, and would happily pay more if I could get it to work again.

Any help would be appreciated!

**Comment by jeaton2i** [comment]
Well, I don't know if someone fixed it, but it magically started working this evening.  Cheers!

**Comment by treksler** [comment]
mine is still broken

**Comment by treksler** [comment]
could be a duplicate of #498

**Comment by swemav** [comment]
Same problem. Tried to disconnect Strava in various ways, private browsers etc as people are talking about here with no success. Connecting with Strava-Endomondo-Dropbox will sync between Endomondo-Dropbox, but Strava never works. Has tried to reauthenticate Strava with tapiriik, same problem. Is there any way of clearing all info on Tapiriik.com for my account and restart?
