### ISSUE TITLE
Stuck on Queuing

### ISSUE THREAD

**Issue by jacoplane** [cpfair/tapiriik#539]
I connected my Endomondo and Strava accounts three days ago, and all I see when I return to the site is "Queuing". Nothing has been synchronized yet. Is it normal for it to take so long?

**Comment by zkauker** [comment]
The same here with Runkeeper & Strava, it's stuck for a day now. I'm a new user of tapiriik, so I'm not sure if this is normal.

**Comment by plysdyret** [comment]
Same here. I even paid for the thing.

**Comment by jacoplane** [comment]
Ok it finally seemed to have worked today. So it took three days to complete.
