### ISSUE TITLE
Endomondo sync private activities

### ISSUE THREAD

**Issue by svenvdmeer** [cpfair/tapiriik#54]
The sync settings from Endomondo doesn't have the option sync private activities. Is it possible to add that?

**Comment by samgam** [comment]
YES, that would be VERY interesting for me as well. I would like to sync hundreds of private workouts just with my dropbox. Thanks a lot!

**Comment by samgam** [comment]
wow, it works! Sync of all workouts is just running. I just had to be patient and wait some hours until sync started.
