### ISSUE TITLE
Website font

### ISSUE THREAD

**Issue by mpomarole** [cpfair/tapiriik#56]
This is just a nit pick. The font of the website is not ideal and makes it hurt to read it. 

Thanks for the awesome project :)

**Comment by cpfair** [comment]
This might be improved with the tweaked colour scheme (font is unchanged).

**Comment by marcin-gryszkalis** [comment]
I like the font but it has real problem - lack of different encodings 
![example of broken chars](https://cloud.githubusercontent.com/assets/1675887/8026272/50812824-0d70-11e5-9e23-8dc79585b6a6.png)
