### ISSUE TITLE
Tapiriik stuck on "queuing", won't sync

### ISSUE THREAD

**Issue by androidunderground** [cpfair/tapiriik#570]
Tapiriik stuck on "queuing" for a week (since October 3, 2022). Won't sync to dropbox from garmin and strava.

**Comment by AndersOhman** [comment]
Also experiencing this issue on the same timeframe. Tried unlinking all accounts, removing permissions, re-adding. Still stuck at queueing.

**Comment by goo3r** [comment]
Same here, stuck on queuing for a few days

**Comment by androidunderground** [comment]
11 oct 2022: everything's syncing again

**Comment by androidunderground** [comment]
11 oct 2022: everything's syncing again
