### ISSUE TITLE
Polar Flow support?

### ISSUE THREAD

**Issue by tmcw** [cpfair/tapiriik#69]
It's not clear if Polar provides an API at all, so this might not be actionable, but if they do and it's just very very poorly advertised, it would be awesome for `tapiriik` to support it.

**Comment by grzeg1** [comment]
Unfortunately I can't understand Python enough to do this myself. But here's PHP code that logs in to Polar Flow, gets a list of activities for date range, fetches TCX for them and saves in /tmp.
Timezone support is broken (or nonexistent) in Flow so TCX files need to be corrected and user has to provide timezone he is in.
If you could work from here it would be great. Looking at how much things are delayed with Polar I would not count on them responding to API access requests in near future :(.

```php
<?php

$user_email = 'email here';
$user_pass = 'password here';

$start_date = '29.12.2014';
$end_date = '8.2.2015';


$post_fields = 'returnUrl=https%3A%2F%2Fflow.polar.com%2F&email=' . $user_email . '&password=' . $user_pass;

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://flow.polar.com/ajaxLogin');
curl_setopt($ch, CURLOPT_COOKIEJAR, '/tmp/cook');
curl_setopt($ch, CURLOPT_COOKIEFILE, '/tmp/cook');
curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

$arr = curl_exec($ch); //get login page

curl_setopt($ch, CURLOPT_URL, 'https://flow.polar.com/login');
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post_fields);

$arr = curl_exec($ch); //post credentials


curl_setopt($ch, CURLOPT_URL, 'https://flow.polar.com/training/getCalendarEvents?start=' . $start_date . '&end=' . $end_date);
curl_setopt($ch, CURLOPT_POST, 0);

$arr = curl_exec($ch); //get activity list

$activity_arr = json_decode($arr);

$tz_fix_offset = '+01:00';

foreach ($activity_arr as $activity) {
    if ($activity->type == 'EXERCISE') {
        echo $activity->url . PHP_EOL;
        $tcxurl = 'https://flow.polar.com' . $activity->url . '/export/tcx';

        echo 'Fetching ' . $tcxurl . "...";
        curl_setopt($ch, CURLOPT_URL, $tcxurl);
        $tcx = curl_exec($ch);
        echo 'done'.PHP_EOL;

        $tcxname = '/tmp/' . $activity->datetime . '.tcx';

        $fixedtcx = str_replace('000Z', '000' . $tz_fix_offset, $tcx);

        file_put_contents($tcxname, $fixedtcx);
    }
}
```

**Comment by boikedamhuis** [comment]
I used your script @grzeg1! Added a little piece of code from this git: https://github.com/jakajancar/DropboxUploader. Now it exports to Dropbox. But I'm not so good with python or php :/

**Comment by Olgagr** [comment]
:+1: for support Polar

**Comment by grzeg1** [comment]
@cpfair you think you could help with this?

**Comment by grzeg1** [comment]
@cpfair any particular reason why you did not add new service label to this one?

**Comment by grzeg1** [comment]
I added Dropbox support with official SDK. Files can be picked up by Tapiriik from there.
https://github.com/grzeg1/polarsync
I was trying to put it into Tapiriik but there are issues:
- to get activity type you have to look into TCX file - it's not in the list
- I still don't know Python well enough ;)

**Comment by boikedamhuis** [comment]
@grzeg1 Awesome, but I have a little error while running in terminal. 

While running in terminal using: PHP /path/ 

-- Fatal error: Uncaught exception 'InvalidArgumentException' with message ''inStream' has bad type; expecting resource, got boolean' in /Users/name/polarsync/dropbox-sdk/Dropbox/Checker.php:22 --

**Comment by grzeg1** [comment]
:) cool

**Comment by grzeg1** [comment]
@cpfair what do you think about incorporating Polar? Lots of people would benefit from Tapiriik sync support.

**Comment by grzeg1** [comment]
updated https://github.com/grzeg1/polarsync for new tcx zip file handling

**Comment by cpfair** [comment]
I'm currently talking with them to see what I might be able to do. Major sticking point right now is that their API is quite a bit different from what tapiriik generally uses, so I don't know if I can make it work.

**Comment by grzeg1** [comment]
And you don't want to do it throught web interface, do you?

**Comment by grzeg1** [comment]
For all of those who miss syncing from Flow but can't do it via Tapiriik: Android SyncMyTracks app is reportedly working well withsyncing across multiple platforms

**Comment by campbellr** [comment]
+1 for Polar Flow support.

 I'd love to help, but unfortunately I never heard back from Polar after requesting access to their API

**Comment by blacknose** [comment]
I also tried to get access to flowsync API but it was denied. Would like to
help too.

2015-03-29 23:49 GMT-03:00 Ryan Campbell <notifications@github.com>:

**Comment by cpfair** [comment]
Here's the 411 on their API, as I understand it after talking with them: It's designed for third-party tracking sites to receive data from Polar hardware in a secure fashion. For instance, a health insurance provider might provide lower premiums to a user who tracks and uploads their fitness activities. It does not permit uploading third-party data, nor does it allow access to data already extant on PPT/Polar Flow - two major differences with the 'standard' fitness API. I've yet to come up with a clever solution to reconcile these traits with how users expect tapiriik to work.

**Comment by grzeg1** [comment]
@cpfair how about using Flow internal api then? That's the way Tapiriik's Endomondo integration used to work at the very beginning. It's not ideal, but it's JSON and no web interface scraping is involved. TCX export is provided too.

**Comment by nah-ko** [comment]
Hello all ! Using @grzeg1 PHP code I've tried to do some python "clone":
https://github.com/nah-ko/PolarTCXFetch
It's just to download TCX files so we can do anything we want then.
@cpfair feel free to use & adapt it as you want to.

**Comment by campbellr** [comment]
I've started working on implementing a tapiriik service for polar flow using the (unofficial) APIs used by their web interface (thanks for the pointer @grzeg1) . I can't promise it will be done any time soon though (or ever, really).

As a first step though I've created a simple stand-alone python library to access the API (https://github.com/campbellr/flow-client), which is already somewhat useful.

**Comment by grzeg1** [comment]
Nice.
Notice that zipfiles for multi-sport activities  (e.g.Triathlon) contain multiple TCX files.

**Comment by jfunction** [comment]
Hi all - I'm also interested in integration with polar flow! 

I'm going to look at the partial solutions proposed on this thread soon. For now I was wondering what the consensus was on accessing the data through google fit? eg, http://www.polar.com/en/connect_with_polar/google_fit_and_apple_healthkit

In the case that this seems like a good idea, perhaps it would be worth trying to resurrect this pull: https://github.com/cpfair/tapiriik/pull/110 
What are our thoughts on that? I'm comfortable with python and happy to help if I can be useful... I'm just wondering where to put my efforts :)

**Comment by grzeg1** [comment]
the description of data transferred on the page you cited does not include e.g GPS samples, so I don't thing it's worth the effort

**Comment by grzeg1** [comment]
@campbellr now that you've done SmashRun you think you could do Flow through unofficial api? ;)

**Comment by campbellr** [comment]
@grzeg1 That's my plan, although i'll probably be busy fixing any lingering issues with the smashrun service for the next little while.

**Comment by blacknose** [comment]
Polar Flow will sync with Strava by the mid of September, so tapiriik can
sync this data from there.
http://updates.polar.com/2015/06/polar-flow-goes-strava/

2015-07-07 17:12 GMT-03:00 Ryan Campbell <notifications@github.com>:

**Comment by grzeg1** [comment]
yeah, only if you take a look at the history of announcements and updates, you'll know that September 2015 in Polar's time will be September 2016 in our time....

**Comment by blacknose** [comment]
Well.. that seems to be true!

**Comment by jfunction** [comment]
It was changed to October some time ago. If November comes and I have some time I'll take a look at this. For now I hear that there are tools which others have found useful - eg http://www.flow2strava.com or https://play.google.com/store/apps/details?id=com.syncmytracks.free

**Comment by desrod** [comment]
@jfunction, it seems odd to use a mobile app to sync multiple non-mobile data sources. 

tapiriik served its purpose, but now that it's not functioning, we should look at updating the tapiriik codebase to bring it to current, or deprecate it entirely and replace it with one that has the code + resources to remain current with the published API of those services it supports. 

I don't want to use my mobile device as a middleman between two online services I consume for my tracking data. It should merely be a console to that data, not a critical component of the workflow, IMHO.

**Comment by jfunction** [comment]
@desrod, as it was suspected Strava integration [won't be ready](http://updates.polar.com/2015/10/schedule-update-on-strava-integration-and-running-programs/) any time soon. My hacky solution was to create 3 bookmarks. 

The first links to https://flow.polar.com/diary where I select the activity I want to move to Strava. 
I wrote the second bookmark like this: 
```javascript
javascript:window.location=window.location.href+"/export/tcx/false";
```
which serves as a quick tcx export button while viewing the run/ride on Polar Flow. I then use my third bookmark linking to https://www.strava.com/upload/select to upload it. 

It still seems like a long way around, but it works in a scalable way in the sense that it's unlikely to break as time goes on. I'm open to hearing other suggestions on code I can write to better automate the process. For example I know [polarsync](https://github.com/grzeg1/polarsync) can automatically pull flow data to disk for you meaning the first and second bookmarks would be scratched out of the process. That's pretty sweet (though it may not be obvious which runs/rides you want to select from disk).

One of the things I wondered about was the metadata Strava allows you to enter after you've uploaded a new run/ride. Eg - title, description and tags for commute or whatever else. I would prefer being able to include this step before I upload my run/ride. Ideally then I would want to have new runs/rides in a queue ready for me to make final edits before completing the sync. 

Comments? Thoughts?

**Comment by tmcw** [comment]
🙏 Polar ↔ Strava is finally done. https://support.strava.com/hc/en-us/articles/216918127-Syncing-between-Strava-and-Polar-

**Comment by tmcw** [comment]
Polar ↔ Strava hits my usecase perfectly. Still using tapiriik to get redundancy across services, and fine with having the entrypoint a little weirdly rube-goldbergy. Closing here; if someone wants to take on the API integration, feel free to open another issue, but I think this usecase is covered.

**Comment by campbellr** [comment]
FWIW, it looks like Polar finally opened up their API:

https://www.polar.com/blog/introducing-polar-open-accesslink-api/

Directly syncing from Polar Flow should be doable now. Unfortunately I don't have the time to implement it in the near future.

**Comment by cpfair** [comment]
"Please note that you can only query new data and don’t have access to
historical data already stored in the Polar Flow service." means this new
API is somewhat unhelpful for many tapiriik use-cases, unfortunately.

**Comment by campbellr** [comment]
Ah, I missed that. That's unfortunate...
