### ISSUE TITLE
Utf-8 for comments

### ISSUE THREAD

**Issue by korjavin** [cpfair/tapiriik#85]
I wrote my activity via runkeeper app and added some comment in russian, like that:
![_649](https://cloud.githubusercontent.com/assets/148765/5519554/57a5d9b0-897c-11e4-9129-16edbb10b009.png)

After transfer it to Endomondo text was broken:
![_647](https://cloud.githubusercontent.com/assets/148765/5519556/69a443c2-897c-11e4-825f-8e4142b2c3fa.png)

**Comment by valery1707** [comment]
Problem still persist :(

**Comment by valery1707** [comment]
File exported to Dropbox contains only question mark and digits.

**Comment by valery1707** [comment]
Any news?

**Comment by vabue** [comment]
Runkeeper to Strava - same problems.

**Comment by valery1707** [comment]
`RunKeeper to Strava` and `RunKeeper to Dropbox` still have encoding problems
