### ISSUE TITLE
Diagnostics doesn't work on fresh vagrant

### ISSUE THREAD

**Issue by mduggan** [cpfair/tapiriik#94]
Not a big problem, but followed the wiki instructions to bring up a new image and went to the diagnostics page. The line:
```
context["autosyncCt"] = db.users.find(User.PaidUserMongoQuery()).count()
```
Fails with this:
```
OperationFailure at /diagnostics/
command SON([('count', 'users'), ('query', {'$or': [{'Payments.Expiry': {'$gt': datetime.datetime(2015, 1, 24, 23, 42, 12, 173819)}}, {'Promos.Expiry': {'$gt': datetime.datetime(2015, 1, 24, 23, 42, 12, 173823)}}, {'Promos.Expiry': {'$exists': True, '$eq': None}}]}), ('fields', None)]) failed: exception: invalid operator: $eq
```

I'm not sure I know enough about the DB to know the "right" fix, and I don't care about this stat during dev so as a work-around I just set it to 0:
```
context["autosyncCt"] = 0
```
Didn't want to add an instruction to do this on the wiki in case there's some nicer way to fix it..

**Comment by cpfair** [comment]
I'm kind of confused about this issue too - that query works great in production, and the operator it's complaining about was specifically added to fix a bug a while back (https://github.com/cpfair/tapiriik/commit/f6a71f4afd76d95032a92959d6fbd3cce93d8a82). What version of Mongo are you running? The production servers are on 2.6.7.

**Comment by mduggan** [comment]
Seems the default one I got on 13.10 was 2.4.6, so that would be it.

**Comment by soalhn** [comment]
I've hit the same bug:
`pymongo.errors.OperationFailure: command SON([('count', 'users'), ('fields', None), ('query', {'$or': [{'Payments.Expiry': {'$gt': datetime.datetime(2015, 2, 5, 13, 32, 48, 504685)}}, {'Promos.Expiry': {'$gt': datetime.datetime(2015, 2, 5, 13, 32, 48, 504688)}}, {'Promos.Expiry': {'$eq': None, '$exists': True}}]})]) on namespace tapiriik.$cmd failed: exception: invalid operator: $eq`

And I can confirm that there's no operator "$eq" on MongoDB:
http://docs.mongodb.org/manual/reference/operator/

There is aggregation framework, but it should be used in a different way:
http://docs.mongodb.org/manual/reference/operator/aggregation/eq/

**Comment by cpfair** [comment]
There's no documented `$eq` operator - but it certainly exists (in newer versions of MongoDB, at least).

![cf](http://ss.cpfx.ca/Labhl.png?v)

The first query shows the undesired behaviour addressed in https://github.com/cpfair/tapiriik/commit/f6a71f4afd76d95032a92959d6fbd3cce93d8a82 - it includes documents where that field is simply unset. The 2nd query returns the same result - as would be expected. The 3rd excludes those unwanted documents, and can be combined with the 2nd to produce the 4th - what's running in production right now.

The last query is an alternate means of arriving at the same result, without undocumented operations. Just pushed that in df44ca3a9223e20935127d246451e0e4b8bdb861.
