### ISSUE TITLE
Endomondo Api ??

### ISSUE THREAD

**Issue by jesperordrup** [cpfair/tapiriik#97]
Hi @cpfair 

As far as I know endomondo has not released a public api. Did you just figure it out?

May I ask if you have seen anything in their api that supports live data. Webhooks or anything?

best
Jesper

**Comment by cpfair** [comment]
They provided me with access to their official API.

Their API does provide real-time webhooks for activity creation, see https://github.com/cpfair/tapiriik/blob/master/tapiriik/services/Endomondo/endomondo.py#L207-221 in particular.

**Comment by jesperordrup** [comment]
Thanks × 2. This is good news.
Den 04/02/2015 15.12 skrev "Collin" <notifications@github.com>:
